### ISSUE TITLE
The error of Init ModeFinder

### ISSUE THREAD

**Issue by DynamicMiner** [KedamaOvO/RealTimePPDisplayer#12]
After I open Sync and osu!,the message shown:
[OsuRTDataProvider][ID:0]Init ModeFinder Failed!Retry after 3 seconds
I tried many times to reinstall the OsuRTData,but useless
The pp calculator doesn't work on Win8 environment?
How can I fix this problem?

**Comment by KedamaOvO** [comment]
Please download ORTDP [1.3.4](https://github.com/OsuSync/OsuRTDataProvider-Release/releases/download/v1.3.4/OsuRTDataProvider-1.3.4.zip), and send **log.txt** for me.
I am trying to find the cause of the problem.
Set **DebugMode = True** in **config.ini**

**Comment by DynamicMiner** [comment]
[Log(Better version).txt](https://github.com/OsuSync/RealTimePPDisplayer/files/1774981/Log.Better.version.txt)
This is the log(... so long)

**Comment by KedamaOvO** [comment]
Can you tell me your operating system and cpu models?

**Comment by DynamicMiner** [comment]
How to find out my CPU model?

**Comment by DynamicMiner** [comment]
Processor : Intel(R) CORE(TM) i3-4130T CPU @ 2.90GHz
Windows edition : Windows 8 Pro
System type : 64-bit OS,x64-based processor

**Comment by KedamaOvO** [comment]
I just released ortdp 1.3.5, you can now  manually select the game mode.
Set GameMode in config.ini. (default: Auto)
Available options: Auto,Osu,CatchTheBeat,Mania,Taiko

**Comment by DynamicMiner** [comment]
Thanks
You are the best!
If have any problem,I'll post issue as fast as possible!
^V^
And you might hate me again...
I find another problem...
After I choose the gamemode
It still doesn't count pp as well...
[Log.txt](https://github.com/OsuSync/RealTimePPDisplayer/files/1775572/Log.txt)
This is the log after I change the GameMode
I hate Windows 8
Sorry for making lots of troubles on you.
TOT + orz

**Comment by DynamicMiner** [comment]
I think I need to send you the file so you might can find some clues.
[Sync-2.17.zip](https://github.com/OsuSync/RealTimePPDisplayer/files/1775582/Sync-2.17.zip)
I follow the rules that prevent the error of plugins.
It says the method not found :
'System.String System.String.Format<System.IFormatProvider, SystemString, SystemObject>'

**Comment by KedamaOvO** [comment]
You also need to upgrade the .net framework to 4.6.

**Comment by DynamicMiner** [comment]
ok

**Comment by DynamicMiner** [comment]
I upgraded to 4.6 but still cant count pp
Now I try 4.6.2
